sonar.projectKey=mary010-sky_web-vulnerabilidad
sonar.organization=mary010-sky
sonar.projectName=Web Vulnerability Scanner
sonar.projectVersion=1.0

sonar.sources=backend,frontend/src
sonar.tests=backend/tests
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/venv*/**,**/*.pyc,backend/scanner.db

sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.sourceEncoding=UTF-8
sonar.python.version=3.11
